### ISSUE TITLE
IExtractorInvokeOptions > showVerboseMessages contain a dead link

### ISSUE THREAD

**Issue by aolyang** [microsoft/rushstack.io-website#30]
I found that [Home > @microsoft/api-extractor > ExtractorLogLevel](https://rushstack.io/pages/api/api-extractor.extractorloglevel/) has no sub-tree any more, 

but 
[Home > @microsoft/api-extractor > IExtractorInvokeOptions > showVerboseMessages](https://rushstack.io/pages/api/api-extractor.iextractorinvokeoptions.showverbosemessages/)
contain a dead link. as follow

// full dead link here
https://rushstack.io/pages/api/api-extractor.iextractorinvokeoptions.showverbosemessages/api-extractor.extractorloglevel.verbose.md

If there is no one currently focus, I would like to help repair it when I'm free later.

**Comment by octogonz** [comment]
This was fixed by the migration to Docusaurus. The new page is here: https://api.rushstack.io/pages/api-extractor.extractorloglevel/
